### ISSUE TITLE
2017080129for week 10

### ISSUE THREAD

**Issue by A-HAMED** [zhushaojun/web2019aut#164]
* Github project url
https://github.com/A-HAMED/2017080129Ahmed-Travel-Agency

* Live demo url
https://eerie-alien-46246.herokuapp.com/

* Describe what you have done since last week

i did project plan

i did presentation

i created my project pages and i used css ,html,bootstrap

i submitted it online

i created readme file

**Comment by zhushaojun** [comment]
not ok 
duplicated with another one
