### ISSUE TITLE
20160021161 , 2016002157 and 2016002142 for week 10

### ISSUE THREAD

**Issue by aissabahriz** [zhushaojun/web2019aut#165]
* Github project URL
https://github.com/aissabahriz/restaurant-management-system/invitations

* Describe what you have done since last week

1. we finished the JSP project for web application
2. and we are working on the Spring project for J2EE Programming since we are relearning students

**Comment by zhushaojun** [comment]
too  late Friday is the deadline for every week
and the project should be done individually

**Comment by aissabahriz** [comment]
Hello laoshi
Sorry for late submit of the project and for the point of the project must
be done individually I didn't know about it because last semester we worked
as groups so I thought it will be the same for this semester too
