### ISSUE TITLE
2017050041

### ISSUE THREAD

**Issue by GINGER94S** [zhushaojun/web2019aut#17]
https://github.com/GINGER94S/INE-PLAY-CENTRE

**Comment by zhushaojun** [comment]
for week 9
## 2019.10.27

1. Make a meaningful name of your projects.
2. If you have finished your work this week, post an issue in my repo. I will check your projects.
3. Put your frontend pages of your projects on [Github Pages](https://pages.github.com/).


## 2019.10.24

Next week before you discuss with me, you should finish following things:
1. Add a readme file, which includes:
   * Titles and internal titles
   * Introduction - the project's aim
   * Technologies
   * Features
   * Plan for whole project
2. Frontend of the home page of your project should be finished.
