### ISSUE TITLE
 for week 11  2017002114

### ISSUE THREAD

**Issue by RAHMANMDMOSTAFIZUR** [zhushaojun/web2019aut#179]
* Github project url
RAHMANMDMOSTAFIZUR/Sports-Score-App

* Live demo url
https://rahmanmdmostafizur.github.io/Sports-Score-App/
* Describe what you have done since last week

1. Learn advanced frontend and backend.
2.  Added all advanced contents .
3. Decorated all pages. Completed frontend.

**Comment by zhushaojun** [comment]
ok for 11
