### ISSUE TITLE
2016006819 week for 11

### ISSUE THREAD

**Issue by rokib042** [zhushaojun/web2019aut#213]
Name: Rokib Miah
About: RUNNING-PRACTICE-WEB-APP
TITLE: 2016006819 for week 11
Labels: ''
Assignees: ''

Description of what I have done since last week
Preparation
firstly I have started by creating my project plan and picking a specific name for my project.

have created some drawings of how I would like my project to look like, I also visit google and YouTube for clarification and for some new ideas.
I watched videos provided by my teacher so as to have the knowledge and to know the tools which are required to do this task.
Mr. Zhu told me to use these tools (vs code, js, Github, bootstrap, and some website to deploy it).
First Procedure 1
After watching Html videos I created all my pages for my website and I migrated to Css and bootstrap and I put CSS codes using videos provided by my teacher.

I combined my CSS codes into one page for neatness and for easy to understand.
Since I have already installed all tasks required, since I am using Linux (deepin), I started pushing my files to the master branch in Github.
I uploaded my Html files, a CSS file and a file containing all the images I used in my web app.
Github Procedure 2
After all the creation of RUNNING-PRACTICE-WEB-APP, i then wrote my read me file on github , here I explained my aim and how I am going to do the project until I am done.

* Github project url
https://github.com/rokib042/RUNNING-PRACTICE-WEB-APP
* Live demo url
https://rokib042.github.io/RUNNING-PRACTICE-WEB-APP/

* Describe what you have done since last week

1.update my website
2. add some content
3. Finish the front end

**Comment by zhushaojun** [comment]
ok for 11
