### ISSUE TITLE
2017080196 - for 9 week

### ISSUE THREAD

**Issue by HOres20** [zhushaojun/web2019aut#25]
https://github.com/HOres20/FilmMonster

**Comment by zhushaojun** [comment]
## 2019.10.30

The plan is like:

* week 8: what will be finished
* week 9: what will be finished
...
* week 16: what will be finished

The title should be： 2017090076 for week 9


## 2019.10.27

1. Make a meaningful name of your projects.
2. If you have finished your work this week, post an issue in my repo. I will check your projects.
3. Put your frontend pages of your projects on [Github Pages](https://pages.github.com/).


## 2019.10.24

Next week before you discuss with me, you should finish following things:
1. Add a readme file, which includes:
   * Titles and internal titles
   * Introduction - the project's aim
   * Technologies
   * Features
   * Plan for whole project
2. Frontend of the home page of your project should be finished.

**Comment by HOres20** [comment]
I am finished my first plan

**Comment by zhushaojun** [comment]
ok for week 9
