### ISSUE TITLE
2017002105 week_09

### ISSUE THREAD

**Issue by jahangirshiblu** [zhushaojun/web2019aut#31]

**Comment by zhushaojun** [comment]
where is the url of your project?

**Comment by jahangirshiblu** [comment]
https://github.com/jahangirshiblu/blood-bank-blood-donar-management-system

**Comment by zhushaojun** [comment]
refer to 
https://github.com/HOres20/FilmMonster
https://github.com/Sierra007117/Digital-DashBoard

**Comment by jahangirshiblu** [comment]
ok.

**Comment by jahangirshiblu** [comment]
i will do that in this week

**Comment by jahangirshiblu** [comment]
https://jahangirshiblu.github.io/blood-bank-blood-donar-management-system/

**Comment by jahangirshiblu** [comment]
https://jahangirshiblu.github.io/blood-bank-blood-donar-management-system/

**Comment by zhushaojun** [comment]
ok for week 9
