### ISSUE TITLE
2017002102 WEEK 9

### ISSUE THREAD

**Issue by TayefShiham** [zhushaojun/web2019aut#34]
Laoshi I have added new project plan.

https://github.com/TayefShiham/House-Collapus

**Comment by zhushaojun** [comment]
add style for you homepage

**Comment by zhushaojun** [comment]
finish the homepage

**Comment by TayefShiham** [comment]
laoshi, finish homepage and added plan for project.

https://github.com/TayefShiham/House-Collapus

**Comment by zhushaojun** [comment]
ok for week 9
