### ISSUE TITLE
2017060069-WEEK 13

### ISSUE THREAD

**Issue by 2017060069-EDWARD** [zhushaojun/web2019aut#366]
*glitch
https://2017060069-edward-npng-github-io.glitch.me/

*GITHUB
https://github.com/2017060069-EDWARD/npng.github.io

WHAT I DID FOR THIS WEEK 

-worked on sign up and sign in
-put the website on glitch
-made the mongodb and started to work on saving user data
-created a heroku account so i can upload to the server
-added jquery to the sign in page
-

**Comment by zhushaojun** [comment]
ok
