### ISSUE TITLE
2017070162

### ISSUE THREAD

**Issue by 2017070162** [zhushaojun/web2019aut#381]
* Github project url
 
https://github.com/2017070162/Child-project

* Live demo url
 https://2017070162-child-project-3.glitch.me/

* Plan
 Week 8 : Github update

Week 9 : Setting home

Week 10 : Making home page responsive

Week 11 : Completion of Front-End

Week 12 : add my project on Glitch

Week 13 : Getting ready the user account with back end technology.

Week 14 : Create and Delete method has been implemented from CRUD operation

week 15 :finished the CRUD operation (* User can create account * User can change the information * User can delete account) and payment method

**Comment by zhushaojun** [comment]
You are going to give a presentation?

**Comment by 2017070162** [comment]
yes I added my PPt
