### ISSUE TITLE
2017080127 for wek 9

### ISSUE THREAD

**Issue by yasmin2017080127** [zhushaojun/web2019aut#54]
https://github.com/yasmin2017080127/coffee-shop-website

**Comment by zhushaojun** [comment]
improve the plan 
set github page

**Comment by yasmin2017080127** [comment]
Okay laoshi

**Comment by yasmin2017080127** [comment]
Hello laoshi i have improved the plan and set a github page

**Comment by zhushaojun** [comment]
ok for week 9
